from getpass import getpass

def menu():
      while True:
           print("")
           print('\033[1;92m <<------ WELCOME------>>')
           print("\033[1;93m")
           print(" << --------PLEASE LOG IN---------->>")
           print("\033[1;96m")
           try:
                x = str(input('\033[1;92mUsername \033[1;93m: '))
                print("")
                e = getpass('\033[1;92mPassword \033[1;93m: ')
                print ("")
                if x=="udoy" and e=="udoy123rahman":
                   print('')
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print(' welcome ======>',x)
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   print("")
                   break
                else:
                      print("")
                      print("")
                      print("")
                      print("")
                      print("\033[1;91m     Wrong Password")
                      print("")
           except Exception:
                      
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("\033[1;91m     Wrong Password")
           except KeyboardInterrupt:
                      print("")
                      print("")
                      print("")
                      print("")
                      print("")
                      print("\033[1;91m     Wrong Password")
menu()
